### ISSUE TITLE
App name

### ISSUE THREAD

**Issue by ronnyporsch** [fontvu/webapps-btu-assignment7#1]
the app name is first listed as "AdventureShop". In the description howver, it is called "AdventureShop Pro". Which one is the correct name? Or ist there supposed to be a pro version with additional features? If yes, what are those features?

**Comment by fontvu** [comment]
Hello,

Sorry for the confusion. The initial idea was AdventureShop Pro, but after a while I thought the "Pro" in name was kinda excessive. I removed it later but forgot the rest.
The final name should be AdventureShop.
