### ISSUE TITLE
IDs

### ISSUE THREAD

**Issue by ronnyporsch** [fontvu/webapps-btu-assignment7#3]
The ID for events is supposed to be auto generated, while the one for customers and products it is manually entered. Is there a specific reasoning behind that?
Also, should IDs be unique and is there a rule to how they should be generated?

**Comment by fontvu** [comment]
This is one of the ideas that I changed my mind halfway of writing the requirements but forgot to make changes for all of them. The ID for events, customers, products should be sequentially generated i.e. start with number 1 and plus one onwards. I guess with generated IDs, they should be unique.
