### ISSUE TITLE
Confirmation of domain model

### ISSUE THREAD

**Issue by ronnyporsch** [fontvu/webapps-btu-assignment7#5]
i have added the domain model to the repo. Can you confirm that this matches your requirements?

**Comment by fontvu** [comment]
It looks ok to me, waiting for confirmation from @ishanism and @ilia-karasev

**Comment by ilia-karasev** [comment]
Looks fine to me.

**Comment by ishanism** [comment]
Just a single comment. Product Catalog should have a name (eg: Hiking gears, water sports gear) as it is a collection of the products.

Everything else is okay.

**Comment by ronnyporsch** [comment]
> Just a single comment. Product Catalog should have a name (eg: Hiking gears, water sports gear) as it is a collection of the products.
> 
> Everything else is okay.

i have changed that now
